"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { CalendarDays, Check, Clock3, Plus, Search, Target, Trash2, X } from "lucide-react";
type Concurso={id:string;orgao:string;cargo:string;banca:string;situacao:string;prova:string|null;inscricao_fim:string|null;prioridade:string;progresso:number;observacoes:string|null};
const vazio={orgao:"",cargo:"",banca:"",situacao:"Inscrito",prova:"",inscricao_fim:"",prioridade:"Média",progresso:0,observacoes:""};
const situacoes=["Pretendo me inscrever","Inscrito","Estudando","Prova realizada","Concluído"];
export default function Home(){
 const [items,setItems]=useState<Concurso[]>([]),[form,setForm]=useState(vazio),[busca,setBusca]=useState(""),[filtro,setFiltro]=useState("Todos"),[aberto,setAberto]=useState(false),[editando,setEditando]=useState<string|null>(null),[carregando,setCarregando]=useState(true),[erro,setErro]=useState(""),[token,setToken]=useState<string|null>(null),[pronto,setPronto]=useState(false),[email,setEmail]=useState(""),[senha,setSenha]=useState(""),[cadastro,setCadastro]=useState(false);
 async function carregar(t=token){if(!t)return;setCarregando(true);setErro("");try{const r=await fetch("/api/concursos",{cache:"no-store",headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error||"Não foi possível carregar.");setItems(d)}catch(e){setErro(e instanceof Error?e.message:"Erro inesperado.")}finally{setCarregando(false)}}
 useEffect(()=>{const t=localStorage.getItem("concursos_token");setToken(t);setPronto(true);if(t)carregar(t);else setCarregando(false)},[]);
 async function autenticar(e:FormEvent){e.preventDefault();setErro("");const r=await fetch("/api/auth",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password:senha,action:cadastro?"signup":"login"})}),d=await r.json();if(!r.ok){setErro(d.error_description||d.msg||d.error||"Não foi possível entrar.");return}if(d.access_token){localStorage.setItem("concursos_token",d.access_token);setToken(d.access_token);await carregar(d.access_token)}else setErro("Conta criada. Confirme seu e-mail e depois entre.")}
 function sair(){localStorage.removeItem("concursos_token");setToken(null);setItems([])}
 const lista=useMemo(()=>items.filter(i=>`${i.orgao} ${i.cargo} ${i.banca}`.toLowerCase().includes(busca.toLowerCase())&&(filtro==="Todos"||i.situacao===filtro)),[items,busca,filtro]);
 const proximas=items.filter(i=>i.prova&&new Date(i.prova+"T12:00:00")>=new Date()).length,media=items.length?Math.round(items.reduce((s,i)=>s+Number(i.progresso),0)/items.length):0;
 function novo(){setEditando(null);setForm(vazio);setAberto(true)}
 function editar(i:Concurso){setEditando(i.id);setForm({orgao:i.orgao,cargo:i.cargo,banca:i.banca||"",situacao:i.situacao,prova:i.prova||"",inscricao_fim:i.inscricao_fim||"",prioridade:i.prioridade,progresso:i.progresso,observacoes:i.observacoes||""});setAberto(true)}
 async function salvar(e:FormEvent){e.preventDefault();setErro("");const r=await fetch(editando?`/api/concursos/${editando}`:"/api/concursos",{method:editando?"PATCH":"POST",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(form)});if(!r.ok){const d=await r.json();setErro(d.error||"Não foi possível salvar.");return}setAberto(false);await carregar()}
 async function excluir(id:string){if(!confirm("Excluir este concurso?"))return;const r=await fetch(`/api/concursos/${id}`,{method:"DELETE",headers:{Authorization:`Bearer ${token}`}});if(r.ok)setItems(a=>a.filter(i=>i.id!==id))}
 const data=(v:string|null)=>v?new Intl.DateTimeFormat("pt-BR").format(new Date(v+"T12:00:00")):"A definir";
 if(!pronto)return null;
 if(!token)return <main className="grid min-h-screen place-items-center bg-[#f5f7fb] p-5"><form onSubmit={autenticar} className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-xl"><p className="text-sm font-bold text-blue-600">PAINEL DE CONCURSOS</p><h1 className="mt-2 text-3xl font-bold">{cadastro?"Criar sua conta":"Acessar seus estudos"}</h1><p className="mt-2 text-slate-500">Seus concursos ficam protegidos em uma conta pessoal.</p>{erro&&<p className="mt-4 rounded-xl bg-amber-50 p-3 text-sm text-amber-900">{erro}</p>}<Campo label="E-mail"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Campo><Campo label="Senha"><input type="password" minLength={6} required value={senha} onChange={e=>setSenha(e.target.value)}/></Campo><button className="mt-6 w-full rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white">{cadastro?"Criar conta":"Entrar"}</button><button type="button" onClick={()=>{setCadastro(!cadastro);setErro("")}} className="mt-4 w-full text-sm font-semibold text-blue-600">{cadastro?"Já tenho uma conta":"Ainda não tenho conta"}</button></form></main>;
 return <main className="min-h-screen bg-[#f5f7fb] text-[#132238]">
  <header className="border-b border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><div><p className="text-sm font-semibold text-blue-600">MEUS ESTUDOS</p><h1 className="text-2xl font-bold tracking-tight">Painel de Concursos</h1></div><div className="flex gap-2"><button onClick={sair} className="rounded-xl border border-slate-200 px-4 py-3 font-semibold">Sair</button><button onClick={novo} className="flex items-center gap-2 rounded-xl bg-blue-600 px-4 py-3 font-semibold text-white hover:bg-blue-700"><Plus size={19}/> Novo concurso</button></div></div></header>
  <div className="mx-auto max-w-7xl px-5 py-7 lg:px-8"><section className="grid gap-4 sm:grid-cols-3"><Resumo icon={<Target/>} label="Concursos cadastrados" value={String(items.length)} tone="blue"/><Resumo icon={<CalendarDays/>} label="Próximas provas" value={String(proximas)} tone="amber"/><Resumo icon={<Check/>} label="Progresso médio" value={`${media}%`} tone="emerald"/></section>
  {erro&&<div className="mt-5 flex gap-3 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><Clock3 className="shrink-0" size={18}/><div><strong>Supabase aguardando configuração.</strong><p className="mt-1">{erro}</p></div></div>}
  <section className="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-col gap-3 border-b border-slate-200 p-4 md:flex-row md:justify-between"><div className="relative w-full md:max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={19}/><input aria-label="Buscar concurso" value={busca} onChange={e=>setBusca(e.target.value)} placeholder="Buscar por órgão, cargo ou banca" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 outline-none focus:border-blue-500"/></div><select aria-label="Filtrar por situação" value={filtro} onChange={e=>setFiltro(e.target.value)} className="rounded-xl border border-slate-200 bg-white px-3 py-2.5"><option>Todos</option>{situacoes.map(s=><option key={s}>{s}</option>)}</select></div>
  {carregando?<p className="p-10 text-center text-slate-500">Carregando concursos...</p>:lista.length===0?<div className="p-12 text-center"><Target className="mx-auto text-slate-300" size={38}/><h2 className="mt-3 font-semibold">Nenhum concurso encontrado</h2><p className="mt-1 text-sm text-slate-500">Cadastre sua primeira inscrição para organizar os estudos.</p></div>:<div className="grid gap-4 p-4 lg:grid-cols-2">{lista.map(i=><article key={i.id} onClick={()=>editar(i)} className="cursor-pointer rounded-2xl border border-slate-200 p-5 transition hover:border-blue-300 hover:shadow-md"><div className="flex justify-between gap-3"><div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${i.prioridade==="Alta"?"bg-red-50 text-red-700":i.prioridade==="Baixa"?"bg-slate-100 text-slate-600":"bg-amber-50 text-amber-700"}`}>Prioridade {i.prioridade.toLowerCase()}</span><h2 className="mt-3 text-lg font-bold">{i.orgao}</h2><p className="text-sm text-slate-600">{i.cargo}</p></div><button aria-label="Excluir" onClick={e=>{e.stopPropagation();excluir(i.id)}} className="h-fit rounded-lg p-2 text-slate-400 hover:bg-red-50 hover:text-red-600"><Trash2 size={18}/></button></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div><p className="text-slate-400">Banca</p><p className="font-medium">{i.banca||"A definir"}</p></div><div><p className="text-slate-400">Data da prova</p><p className="font-medium">{data(i.prova)}</p></div></div><div className="mt-5"><div className="flex justify-between text-sm"><span className="font-medium">{i.situacao}</span><span>{i.progresso}%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-blue-600" style={{width:`${i.progresso}%`}}/></div></div></article>)}</div>}</section></div>
  {aberto&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-slate-950/45 sm:items-center sm:p-5"><form onSubmit={salvar} className="max-h-[95vh] w-full max-w-2xl overflow-y-auto rounded-t-3xl bg-white p-6 shadow-2xl sm:rounded-3xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{editando?"Editar concurso":"Novo concurso"}</h2><p className="mt-1 text-sm text-slate-500">Registre a inscrição e acompanhe sua preparação.</p></div><button type="button" onClick={()=>setAberto(false)} className="rounded-full p-2 hover:bg-slate-100"><X/></button></div><div className="mt-4 grid gap-x-4 sm:grid-cols-2"><Campo label="Órgão / concurso"><input required value={form.orgao} onChange={e=>setForm({...form,orgao:e.target.value})}/></Campo><Campo label="Cargo"><input required value={form.cargo} onChange={e=>setForm({...form,cargo:e.target.value})}/></Campo><Campo label="Banca"><input value={form.banca} onChange={e=>setForm({...form,banca:e.target.value})}/></Campo><Campo label="Situação"><select value={form.situacao} onChange={e=>setForm({...form,situacao:e.target.value})}>{situacoes.map(s=><option key={s}>{s}</option>)}</select></Campo><Campo label="Fim das inscrições"><input type="date" value={form.inscricao_fim} onChange={e=>setForm({...form,inscricao_fim:e.target.value})}/></Campo><Campo label="Data da prova"><input type="date" value={form.prova} onChange={e=>setForm({...form,prova:e.target.value})}/></Campo><Campo label="Prioridade"><select value={form.prioridade} onChange={e=>setForm({...form,prioridade:e.target.value})}>{["Alta","Média","Baixa"].map(s=><option key={s}>{s}</option>)}</select></Campo><Campo label={`Progresso: ${form.progresso}%`}><input type="range" min="0" max="100" step="5" value={form.progresso} onChange={e=>setForm({...form,progresso:Number(e.target.value)})}/></Campo></div><Campo label="Observações"><textarea rows={3} value={form.observacoes} onChange={e=>setForm({...form,observacoes:e.target.value})}/></Campo><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={()=>setAberto(false)} className="rounded-xl border border-slate-200 px-5 py-2.5 font-semibold">Cancelar</button><button className="rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white">Salvar concurso</button></div></form></div>}
 </main>
}
function Resumo({icon,label,value,tone}:{icon:React.ReactNode;label:string;value:string;tone:string}){const c:Record<string,string>={blue:"bg-blue-50 text-blue-600",amber:"bg-amber-50 text-amber-600",emerald:"bg-emerald-50 text-emerald-600"};return <article className="flex items-center gap-4 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className={`rounded-xl p-3 ${c[tone]}`}>{icon}</div><div><p className="text-sm text-slate-500">{label}</p><p className="text-2xl font-bold">{value}</p></div></article>}
function Campo({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-4 block text-sm font-semibold text-slate-700">{label}<div className="mt-1 [&>*]:w-full [&>*]:rounded-xl [&>*]:border [&>*]:border-slate-200 [&>*]:bg-white [&>*]:px-3 [&>*]:py-2.5 [&>*]:font-normal [&>*]:outline-none focus-within:[&>*]:border-blue-500">{children}</div></label>}
